pipeline{
    agent any

    environment {
        PROJECT_DIR = "circus_ride_api"
    }

    triggers{
        pollSCM('* * * * *')
    }

    stages{
        stage('Build'){
            // agent {
            //     docker {
            //         image 'maven:ibmjava'
            //         reuseNode true
            //     }
            // }

            steps{
                sh '''
                    mvn -v
                    java -version
                    mvn -f $PROJECT_DIR/pom.xml clean package 
                '''
            }
        }

        stage('Test'){
            steps{
                sh '''
                    echo "Bye World"
                    echo "We are testing the project"
                '''
            }
        }
    }
}