@startuml social-multiplication
!include <C4/C4_Component>

title Social Multiplication Component Diagram for Social Multiplication v1-v4

Person(person, "Anonymous User", "anyone using our application")

Container(web_app, "Web App", "Java, Spring MVC", "Main point for client interaction with our app")
Container(spa, "SPA", "HTML, CSS, Javascipt", "Renders the interface for the web app")

System_Boundary(boundary, "Social Multiplication API", ){
    System_Boundary(allControllers, "App Controllers"){
        Component(controllerApp, "AppControllers", "Spring MVC, RestController")
    }

    System_Boundary(allServices, "App Services"){
        Component(service1, "MultiplicationService", "", "Generates random Multiplications for user to solve")
        Component(helper1, "RandomFactorGeneratorService", "java.utils.Random", "Generates Random Factors for the MultiplicationService")
    }

    System_Boundary(allRepositories, "App Repositories"){
        Component(repoApp, "AppRepository", "JPA", "Represents all our repositories")
    }

    System_Boundary(allDomains, "App Domains"){
        Component(domainModel, "AppDomain", "", "Represents the Model of Domain")
    }
}

ContainerDb(db, "Database", "H2, jdbc")

Rel(person, web_app, "Solves questions on", "HTTP/S")
Rel(spa, web_app, "Provides UI for")
Rel(spa, controllerApp, "Makes API calls to", "HTTP/S")
Rel(repoApp, db, "Store app data")

Rel(helper1, service1, "Generates factors for")
Rel(service1, repoApp, "Queries Database through")
Rel(controllerApp, service1, "Passes Requests to")

@enduml